# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('f_name', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=8)),
                ('mob', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=70)),
                ('address', models.CharField(max_length=100)),
                ('pic', models.FileField(upload_to='')),
            ],
        ),
    ]
